name: Daily Merge + Import

on:
  schedule:
    - cron: "5 4 * * *"   # her gün 04:05 UTC ≈ 06:05 CET/CEST (Berlin)
  workflow_dispatch: {}    # isterse elle de tetiklersin

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "supabase==2.*" python-dateutil

      - name: Merge KAP+Bilanco & Import to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python scripts/merge_kap_bilanco.py
