name: data-build

on:
workflow_dispatch:
schedule:
# 04:30 ve 16:30 Europe/Berlin ≈ 02:30 ve 14:30 UTC
- cron: '30 2,14 * * *'

# push ile tetiklemeyi istersen (opsiyonel):
# push:
# paths:
# - 'scripts/**'
# - 'kap_json/**'
# - 'bilanco_json/**'

permissions:
contents: write # docs/ içine commit-push için gerekli

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4
with:
fetch-depth: 0

- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.11'
cache: 'pip'

- name: Install dependencies (if any)
run: |
if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

- name: Run ETL (KAP + bilanço -> final/*.json)
run: |
# ⬇️ Burayı kendi script’lerine göre düzenle
# Örnek:
# python scripts/kap_to_json.py
# python scripts/bilanco_to_json.py
# python scripts/merge_to_final.py
echo "ETL step is project-specific; adjust this step."

- name: Build index.json & prepare docs/
run: |
python scripts/build_index.py

- name: Commit & push docs/
run: |
mkdir -p docs
touch docs/.nojekyll
git config user.name "github-actions"
git config user.email "github-actions@github.com"
git add docs/
if git diff --quiet --cached; then
echo "No changes to commit."
else
git commit -m "chore: update data (automated)"
git push
fi
