name: data-build

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2,14 * * *'  # 02:30 ve 14:30 UTC (Berlin 04:30 / 16:30 civarı)

permissions:
  contents: write  # docs/ klasörüne commit atmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: |
          python -V
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run ETL (şimdilik boş)
        run: |
          echo "ETL adımını sonra kendi scriptlerinle dolduracağız."

      - name: Build index.json & prepare docs/
        run: |
          python scripts/build_index.py

      - name: Commit & push docs/
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          if git diff --quiet --cached; then
            echo "No changes to commit."
          else
            git commit -m "chore: update data (automated)"
            git push
          fi
